
#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#if 0
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_DBG
#define LOG_CONF_LEVEL_TCPIP LOG_LEVEL_DBG
#endif

#define UIP_CONF_UDP 1
#define UIP_CONF_ROUTER 1
#define UIP_CONF_BUFFER_SIZE	4096

// #define NETSTACK_CONF_NETWORK MAKE_NET_NULLNET
// #define NETSTACK_CONF_FRAMER no_framer
// #define MAKE_ROUTING MAKE_ROUTING_NULLROUTING
#endif /* PROJECT_CONF_H_ */
